---
language: c
dist: xenial
addons:
  apt:
    packages:
      - ansible

install:
  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the roles syntax
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

  # Run the role
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --become"

  # Run the role again, checking to make sure it's idempotent: verbose version.
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --become"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
